# This workflow runs the Flask application with Celery and Redis.

name: Run Flask Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Start Flask app
      run: |
        gunicorn --bind 0.0.0.0:5000 --daemon "run:app"

    - name: Start Celery worker
      run: |
        celery -A celery_worker.celery worker --loglevel=info &

    - name: Wait for application to start
      run: sleep 10 # Give the app and worker time to start

    - name: Test application accessibility
      run: |
        curl http://localhost:5000/
        curl http://localhost:5000/test-celery
